<?php

namespace App\Providers;

use Illuminate\Support\Facades\Gate;
use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Str;
use Symfony\Component\Finder\Finder;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     */
    public function register(): void
    {
        //
    }

    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        $this->registerPolicies();
    }

    /**
     * Explicitly register every {Domain}\{Model}Policy generated by Filament
     * Shield against its App\Models\{Domain}\{Model} counterpart. Our models
     * are domain-namespaced (App\Models\Core\Company, etc.), which Laravel's
     * built-in policy auto-discovery is not guaranteed to guess correctly —
     * so this is done explicitly rather than relying on convention, per
     * shield:generate's own "requires registration" notice and PRD Key
     * Business Rule #6 ("permission must be checked server-side").
     */
    protected function registerPolicies(): void
    {
        $policyPath = app_path('Policies');

        if (! is_dir($policyPath)) {
            return;
        }

        foreach ((new Finder)->files()->in($policyPath)->name('*Policy.php') as $file) {
            $relative = Str::of($file->getRelativePathname())
                ->replace(['/', '.php'], ['\\', ''])
                ->toString();

            $policyClass = "App\\Policies\\{$relative}";

            if (! class_exists($policyClass)) {
                continue;
            }

            // RolePolicy is the one Shield-generated policy for a package model
            // (Spatie\Permission\Models\Role) rather than an App\Models\* class.
            $modelClass = $relative === 'RolePolicy'
                ? \Spatie\Permission\Models\Role::class
                : 'App\\Models\\'.Str::replaceLast('Policy', '', $relative);

            if (class_exists($modelClass)) {
                Gate::policy($modelClass, $policyClass);
            }
        }
    }
}
